version: "3"
services:
  soapysdr:
    build: .
    container_name: soapysdr
    ports:
      - "55132:55132/tcp"
    environment:
      SOAPY_REMOTE_IP_ADDRESS: [::]
      SOAPY_REMOTE_PORT: 55132
    devices:
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
      - /dev/bus/usb/001/005:/dev/bus/usb/001/005
      - /dev/bus/usb/001/006:/dev/bus/usb/001/006
      - /dev/bus/usb/001/007:/dev/bus/usb/001/007
    restart: unless-stopped
